### ISSUE TITLE
claim repo is not thread safe

### ISSUE THREAD

**Issue by tranvictor** [SmartPool/smartpool-client#28]

**Comment by tranvictor** [comment]
```
fatal error: .concurrent map iteration and map write

goroutine 31 [running]:
runtime.throw(0x9e2361, 0x26)
        /usr/lib/go-1.8/src/runtime/panic.go:596 +0x95 fp=0xc421460d20 sp=0xc421460d00
runtime.mapiternext(0xc421460f18)
        /usr/lib/go-1.8/src/runtime/hashmap.go:737 +0x7ee fp=0xc421460dd0 sp=0xc421460d20
github.com/SmartPool/smartpool-client/ethereum.(*TimestampClaimRepo).Persist(0xc420743c20, 0xe98c60, 0xc4200d7580, 0x2, 0xc4207efd80)
        /home/eth10ai/smartpool-client/build/_workspace/src/github.com/SmartPool/smartpool-client/ethereum/timestamp_claim_repo.go:179 +0x379 fp=0xc421460f88 sp=0xc421460dd0
github.com/SmartPool/smartpool-client/protocol.(*SmartPool).persist(0xc420088240)
        /home/eth10ai/smartpool-client/build/_workspace/src/github.com/SmartPool/smartpool-client/protocol/smartpool.go:255 +0x4a fp=0xc421460fc0 sp=0xc421460f88
github.com/SmartPool/smartpool-client/protocol.(*SmartPool).runPersister(0xc420088240)
        /home/eth10ai/smartpool-client/build/_workspace/src/github.com/SmartPool/smartpool-client/protocol/smartpool.go:249 +0x2b fp=0xc421460fd8 sp=0xc421460fc0
runtime.goexit()
        /usr/lib/go-1.8/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc421460fe0 sp=0xc421460fd8
created by github.com/SmartPool/smartpool-client/protocol.(*SmartPool).Run
        /home/eth10ai/smartpool-client/build/_workspace/src/github.com/SmartPool/smartpool-client/protocol/smartpool.go:317 +0x2a0
```
